#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
DISCOVER_SCRIPT="${SCRIPT_DIR}/discover-tunnel-ip.sh"
NVPN_CONFIG_DIR="${ROOT_DIR}/nvpn-config"
NVPN_CONFIG_FILE="${NVPN_CONFIG_DIR}/config.toml"

generate_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${bytes}"
  else
    head -c "${bytes}" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

get_env_value() {
  local key="$1"
  if [[ ! -f "${ENV_FILE}" ]]; then
    echo ""
    return
  fi
  grep -E "^${key}=" "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true
}

upsert_env() {
  local key="$1"
  local value="$2"
  local tmp_file

  if [[ ! -f "${ENV_FILE}" ]]; then
    printf '%s=%s\n' "${key}" "${value}" > "${ENV_FILE}"
    return
  fi

  tmp_file="$(mktemp)"
  awk -v k="${key}" -v v="${value}" '
    BEGIN { updated = 0 }
    $0 ~ "^" k "=" {
      if (updated == 0) {
        print k "=" v
        updated = 1
      }
      next
    }
    { print }
    END {
      if (updated == 0) {
        print k "=" v
      }
    }
  ' "${ENV_FILE}" > "${tmp_file}"
  mv "${tmp_file}" "${ENV_FILE}"
}

remove_env_key() {
  local key="$1"
  local tmp_file

  if [[ ! -f "${ENV_FILE}" ]]; then
    return
  fi

  tmp_file="$(mktemp)"
  awk -v k="${key}" '$0 !~ "^" k "=" { print }' "${ENV_FILE}" > "${tmp_file}"
  mv "${tmp_file}" "${ENV_FILE}"
}

is_secret_hex() {
  local value="$1"
  [[ "${value}" =~ ^[a-fA-F0-9]{64}$ ]]
}

contains_bracketed_ipv6() {
  local value="$1"
  [[ "${value}" =~ \[[0-9a-fA-F:]+\] ]]
}

ensure_nvpn_config() {
  mkdir -p "${NVPN_CONFIG_DIR}"

  if [[ -f "${NVPN_CONFIG_FILE}" ]]; then
    return
  fi

  cat > "${NVPN_CONFIG_FILE}" <<'EOF'
# Generated by scripts/init-env.sh.
# Fill participant_npub with your node's npub, then run scripts/mesh-init.sh.

network_id = "nostrmesh-dev"
participant_npub = ""
listen_port = 51820

signal_relays = [
  "wss://relay.damus.io",
  "wss://relay.primal.net"
]
EOF
}

mkdir -p "${ROOT_DIR}"
touch "${ENV_FILE}"
ensure_nvpn_config

secret="$(get_env_value SECRET)"
if [[ -z "${secret}" ]]; then
  secret="$(generate_hex 128)"
fi

nostr_secret="$(get_env_value NOSTR_SECRET_KEY)"
if ! is_secret_hex "${nostr_secret}"; then
  nostr_secret="$(generate_hex 32)"
fi

api_port="$(get_env_value API_PORT)"
if [[ -z "${api_port}" ]]; then
  api_port="4000"
fi

relay_url="$(get_env_value RELAY_URL)"
if [[ -z "${relay_url}" ]]; then
  relay_url="ws://nostrmesh-relay:8008"
fi

blossom_url="$(get_env_value BLOSSOM_URL)"
if [[ -z "${blossom_url}" ]]; then
  blossom_url="http://nostrmesh-blossom:3000"
fi

nvpn_config="$(get_env_value NVPN_CONFIG)"
if [[ -z "${nvpn_config}" ]]; then
  nvpn_config="/config/config.toml"
fi

tunnel_ip=""
if [[ -x "${DISCOVER_SCRIPT}" ]]; then
  tunnel_ip="$("${DISCOVER_SCRIPT}" || true)"
fi

if [[ -n "${tunnel_ip}" ]]; then
  blossom_public_url="http://${tunnel_ip}:3000"
  relay_public_url="ws://${tunnel_ip}:8008"
else
  blossom_public_url="$(get_env_value BLOSSOM_PUBLIC_URL)"
  relay_public_url="$(get_env_value RELAY_PUBLIC_URL)"

  if [[ -z "${blossom_public_url}" ]] || contains_bracketed_ipv6 "${blossom_public_url}"; then
    blossom_public_url="http://localhost:3000"
  fi
  if [[ -z "${relay_public_url}" ]] || contains_bracketed_ipv6 "${relay_public_url}"; then
    relay_public_url="ws://localhost:8008"
  fi
fi

upsert_env SECRET "${secret}"
upsert_env NOSTR_SECRET_KEY "${nostr_secret}"
upsert_env API_PORT "${api_port}"
upsert_env RELAY_URL "${relay_url}"
upsert_env BLOSSOM_URL "${blossom_url}"
upsert_env BLOSSOM_PUBLIC_URL "${blossom_public_url}"
upsert_env RELAY_PUBLIC_URL "${relay_public_url}"
upsert_env NVPN_CONFIG "${nvpn_config}"

if [[ -n "${tunnel_ip}" ]]; then
  upsert_env NVPN_TUNNEL_IP "${tunnel_ip}"
else
  remove_env_key NVPN_TUNNEL_IP
fi

remove_env_key NOSTREAM_BUILD_CONTEXT
remove_env_key YGGDRASIL_LISTEN_PORT

echo "Initialized ${ENV_FILE}"
echo "- BLOSSOM_PUBLIC_URL=${blossom_public_url}"
echo "- RELAY_PUBLIC_URL=${relay_public_url}"
if [[ -n "${tunnel_ip}" ]]; then
  echo "- NVPN_TUNNEL_IP=${tunnel_ip}"
else
  echo "- NVPN_TUNNEL_IP not detected yet"
fi
